### ISSUE TITLE
about the classification model

### ISSUE THREAD

**Issue by caiyuefeng99** [Yangr116/ScalableViT#3]
Hello, I'm very interested in your work. Can you provide more pre-training models about the classification? It will be very helpful to me. Thank you！

**Comment by Yangr116** [comment]
ref: https://github.com/Yangr116/ScalableViT/tree/main/image_classification, I released the weight of the model-S.

**Comment by Yangr116** [comment]
Base and large models have been released, please check  https://github.com/Yangr116/ScalableViT/tree/main/image_classification

**Comment by caiyuefeng99** [comment]
Thank you！
